### PR TITLE
feat: add support for Kong Portal Developers

### PR DESCRIPTION
**Pull request by ChristianJacquot**
This PR add developers as a ressource for Deck. So, they can be persisted.

I would like the meta of a Developer to be displayed as a Map in Deck file. So, I keep this as a draft for now.

### CODE REVIEW

**Comment by ChristianJacquot** [comment]
The meta of a Developer is now displayed as a Map in Deck file. So, this MR is ready for your approval

**Comment by hbagdi** [comment]
@ChristianJacquot Could you elaborate on what is the problem that you are trying to solve that you need this feature?
Developers are created dynamically and an Infrastructure As Code technique doesn't quite add up.

**Comment by ademar59** [comment]
Is there a chance this feature will see the light of day?
We create developers as code and I would like to be able to extract, synchronize developers between several dev portals.

**Comment by hbagdi** [comment]
Closing this because this never saw the light of the day due to other priorities.

**Pull request closed without merging**
