### PR TITLE
feat: add support for Kong Enterprise RBAC resources

### LINKED ISSUE #270: feature: Manage RBAC Entities
## Problem
My team currently leverages Kong's Enterprise Edition RBAC features to manage access to our control-plane. 

We currently use some custom tooling that depends on [go-kong](https://github.com/kong/go-kong) to create custom roles, but we'd prefer to manage RBAC roles (and their associated endpoints and permissions) in a declarative format. i.e.

```yaml
_format_version: "1.1"
services:
- connect_timeout: 60000
  host: localhost
  name: foo-service
  path: /
  port: 8001
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  tags:
  - foo
  routes:
  - id: 6c6a94ff-4404-4e80-8c57-e6506eea4492
    paths:
    - /foo
    path_handling: v0
    preserve_host: false
    protocols:
    - http
    regex_priority: 0
    strip_path: true
    tags:
    - foo
    https_redirect_status_code: 426
plugins:
- name: rate-limiting
  config:
    day: null
    header_name: null
    hour: 10000
    limit_by: consumer
    minute: null
    month: null
    path: null
    policy: local
    second: null
    year: null
  enabled: true
  protocols:
  - grpc
  - grpcs
  - http
  - https
rbac_roles:
- name: admin
  comment: Full access to all endpoints, across all workspaces—except RBAC Admin API
  is_default: false
  endpoint_permissions:
  - workspace: '*'
    endpoint: '*'
    actions:
    - delete
    - create
    - update
    - read
    negative: false
  - workspace: '*'
    endpoint: /rbac/*
    actions:
    - delete
    - create
    - update
    - read
    negative: true
  - workspace: '*'
    endpoint: /rbac/*/*
    actions:
    - delete
    - create
    - update
    - read
    negative: true
  - workspace: '*'
    endpoint: /rbac/*/*/*
    actions:
    - delete
    - create
    - update
    - read
    negative: true
  - workspace: '*'
    endpoint: /rbac/*/*/*/*
    actions:
    - delete
    - create
    - update
    - read
    negative: true
  - workspace: '*'
    endpoint: /rbac/*/*/*/*/*
    actions:
    - delete
    - create
    - update
    - read
    negative: true
- name: super-admin
  comment: Full access to all endpoints, across all workspaces
  is_default: false
  endpoint_permissions:
  - workspace: '*'
    endpoint: '*'
    actions:
    - delete
    - create
    - update
    - read
    negative: false
```

## Entities

* RBACRole
* RBACEndpointPermission
* RBACEntityPermission

I have about 60% of this work complete but would like to get an issue up to track the feature.

### PR DESCRIPTION
**Pull request by hbagdi**
This takes the patch from #271 and adds in some machinery to avoid any potential breakage for existing users.
Please see https://github.com/Kong/deck/pull/271#issuecomment-785917323 for reasoning behind additional commits on top of the initial patch.
Please review commit-by-commit.

Fix #270

### CODE REVIEW

**Comment by hbagdi** [comment]
cc @tjrivera

**Comment by rainest** [comment]
Issues and points of interest found in user/black box testing:
- Endpoint permissions with a non-existent workspace simply fail and no `_workspace` simply fail:
  ```
  while processing event: {Create} rbac-endpointpermission 22021df1-864f-42db-a477-74860a659c87-nonono-* failed: HTTP status 404 (message: "Workspace nonono does not exist")
  ```
  This is probably expected--decK normally requires you handle all transactions on a per-workspace basis. This poses a bit of a challenge since roles with permissions in multiple workspaces are supported, albeit not perfectly (the GUI doesn't really handle them effectively).
- `reset` lacks the `--rbac-resources-only` flag. It does not reset RBAC resources when run without it.
- Roles with no name cause a segfault: [no-name.yaml.txt](https://github.com/Kong/deck/files/6045989/no-name.yaml.txt)
- Permissions with no workspace cause a segfault: [no-workspace.yaml.txt](https://github.com/Kong/deck/files/6046010/no-workspace.yaml.txt)

**Comment by rainest** [comment]
Some of the above are easy to fix: https://github.com/Kong/deck/pull/278

- Roles without names segfaulting isn't easy to address within the existing structure of `file/builder.go`. We don't have any existing pattern of logging and skipping invalid resources or returning errors when this happens, and other resources, e.g. [services](https://github.com/Kong/deck/blob/v1.4.0/file/builder.go#L420) appear to have a similar segfault path. We could do something like this:
  ```
          for _, r := range b.targetContent.RBACRoles {
                  r := r
                  if utils.Empty(r.ID) {
  +                       if utils.Empty(r.Name) {
  +                               b.err = errors.New("RBAC role lacks name")
  +                               return
  +                       }
                          role, err := b.currentState.RBACRoles.Get(*r.Name)
  ```
  though that's not particularly graceful, since it just fails state building entirely and doesn't proceed onward. Functionally that's equivalent to the segfault, though it's a bit less ugly.
- DELETEs not working is due to some odd admin API behavior. Permission admin API endpoints include the permission endpoint in the path, and the permission sometimes includes a leading slash (e.g. `/acls`) and sometimes does not (`*` is the only such endpoint AFAIK). Calls from Manager omit the leading slash, e.g. `DELETE /rbac/roles/a79bdf2b-8844-424d-b6fc-97490cc6fe1d/endpoints/default/acls/*`, whereas we include it `DELETE /rbac/roles/a79bdf2b-8844-424d-b6fc-97490cc6fe1d/endpoints/default//acls/*`. Our PATCHes also use the double slash, but for some reason, those succeed, whereas DELETEs do not (rather, they 204, but the permission remains). We can't just chop that leading slash off entirely with something like:
  ```
  @@ -18,6 +19,8 @@ func rbacEndpointPermissionFromStruct(arg diff.Event) *state.RBACEndpointPermiss
                  panic("unexpected type, expected *state.RBACEndpointPermission")
          }
 
  +       trimmed := strings.TrimLeft(*ep.Endpoint, "/")
  +       ep.Endpoint = &trimmed
          return ep
   }
  ```
  since that makes PATCHEs start 404ing--they _require_ the `//`. DELETEs succeed, though they do throw a spurious `while post processing event: entity not found` after. POSTs succeed, since Kong accepts a body like `{"workspace":"*","endpoint":"wat","actions":"delete,create,update,read"}` (it automatically appends the leading `/`). The discrepancy in the verb behaviors suggests we'd need to handle this in go-kong with endpoint-specific logic. We apparently already have that for [GETs](https://github.com/Kong/go-kong/blob/v0.15.0/kong/endpoint_permission_service.go#L51), but not for [DELETEs](https://github.com/Kong/go-kong/blob/v0.15.0/kong/endpoint_permission_service.go#L112).

**Comment by hbagdi** [comment]
Thanks for the great feedback @rainest!

> Endpoint permissions with a non-existent workspace simply fail and no _workspace simply fail

As you said, we can't do anything about this.

> Roles with no name cause a segfault

> Permissions with no workspace cause a segfault

We can take care of this using https://github.com/Kong/deck/pull/278#discussion_r583425002

> Permission deletes do not work

This is solvable. We need to change the endpoint when it is passed on to go-kong and not in the FromStruct method. That will delete the permission in Kong and not cause the postProcess error.

**Comment by hbagdi** [comment]
@tjrivera Would you mind taking this PR for a spin and letting us know if it works for your environment and use-case?
@rainest Any other comments?

**Review by rainest — APPROVED** [review]
Nah, other than the now-fixed issues I mentioned previously, everything worked as I'd expect. Good to go from my perspective.

**Comment by tjrivera** [comment]
I was able to build and test this branch today. Everything works as expected. Thanks, @hbagdi, and @rainest for the help in getting this over the finish line!

**Comment by hbagdi** [comment]
Amazing, thanks for all your hard work and making this possible, @tjrivera!

**Comment by hbagdi** [comment]
@tjrivera FYI, we will have a release of decK with a few other features in a couple of weeks and this will be included then.

**Comment by tjrivera** [comment]
Awesome! great to see! Thanks @hbagdi and @rainest!

**Pull request merged**
