### PR TITLE
tests: add kong:latest to integration tests matrix

### PR DESCRIPTION
**Pull request by GGabriele**

### CODE REVIEW

**Comment by hbagdi** [comment]
> Do we want latest or nightly/what was the goal here? latest is always some released version and we usually just add the new semver tag once it's out (e.g. currently latest is just 2.8).

I think Travis is correct.
The correct tag for tip of the development branch is `kong/kong:latest`, @gszr could you confirm that for us, please?

**Comment by gszr** [comment]
> > Do we want latest or nightly/what was the goal here? latest is always some released version and we usually just add the new semver tag once it's out (e.g. currently latest is just 2.8).
> 
> I think Travis is correct. The correct tag for tip of the development branch is `kong/kong:latest`, @gszr could you confirm that for us, please?

Your interpretation is correct. A new build is triggered for each new commit merged into `master`; these builds are pushed to `kong/kong`, as you mentioned. Docker label `org.opencontainers.image.revision` is the sha of the commit it was built on top of.

Note `kong/kong` differs from `kong`. Former is for our "unofficial" builds (built / pushed by ourselves), while the latter is our official Docker Library image, curated by the Docker library maintainers.

(My apologies I missed this mention - thanks @GGabriele for pinging me)

**Comment by GGabriele** [comment]
Thanks for confirming this @gszr !

It seems we need to tweak this a bit, since some utils complains about the fetched config not being semver but a timestamp

```
unknown Kong version : '20220509-1608'
```

**Comment by hbagdi** [comment]
@mikefero Another problem with the version of the dev branch builds. ^

**Review by hbagdi — APPROVED** [review]

**Pull request merged**
