### PR TITLE
Feature/cache modules

### PR DESCRIPTION
**Pull request by mmorel-35**

### CODE REVIEW

**Comment by hbagdi** [comment]
The CI says cache hit occured in the first run. That seems odd, any idea whats going on?

**Comment by mmorel-35** [comment]
which run ? 
image

**Comment by hbagdi** [comment]
The post run of that same build.
Actually, there is a bug here. You want to populate cache _after_ you check out the repo. There is no go.sum file when you populate the cache here.

**Review by mflendrich — COMMENTED** [review]
As Harry said above :point_up_2:, please fix the job order and re-request review

**Comment by mmorel-35** [comment]
@mflendrich, that's what I just did with 6ee7fd5

**Review by mflendrich — APPROVED** [review]
LGTM. Seems that I reviewed an old version when I was making my previous comment.

**Comment by mmorel-35** [comment]
This incompatible with Golangci

**Pull request closed without merging**
