### PR TITLE
doc: add asdf deck plugin install infos

### PR DESCRIPTION
**Pull request by nutellinoit**
Hello,

I added infos in the README to install the asdf plugin for deck.
The plugin is available on asdf plugins, It was accepted and merged this PR: https://github.com/asdf-vm/asdf-plugins/pull/509

### CODE REVIEW

**Comment by hbagdi** [comment]
We don't currently track any such third-party integrations within this repo because it creates a maintenance burden:
- integrations get out of date
- there are far too many integrations

@lena-larionova Is this something that is suitable for plugin Hub?

**Comment by lena-larionova** [comment]
@hbagdi the plugin hub is currently in the same situation. At the moment, we're only accepting plugin submissions to our plugin hub from trusted technical partners, on a limited basis. We are not accepting new additions otherwise, as it's a maintenance burden and we can't guarantee quality. 

This might change in the future, but we don't have a timeline for this right now.

**Comment by hbagdi** [comment]
@nutellinoit I'm sorry but we can't accept your contribution in such a case.
A couple of things you can do:
- Announce this as a discussion item [here](https://github.com/Kong/kong/discussions).
- Announce this in [Kong nation](https://discuss.konghq.com/).

Thank you for all you do!

**Comment by nutellinoit** [comment]
Thank you!

**Pull request closed without merging**
